#! /bin/sh

port="10873"
# if [[ $1 == 1 ]]
# then
#   port="20873"
# elif [[ $1 == 2 ]]
# then
#   port="30873"
# fi

RSYNC_PASSWORD=alpine rsync -av --no-perms --no-owner --no-group --exclude '.svn*' --exclude '*.c' --exclude '*.h' --exclude '*.o' --exclude '*.cpp' --exclude '*.a' --exclude '.hg*' --exclude 'Makefile'  $1 rsync://root@localhost:$port/root/private/var/kb/$2
